FROM python:latest

WORKDIR /code

COPY ../RealEstateSubscriptionInfo/requirements.txt ./code/requirements.txt

RUN pip install -r ./code/requirements.txt

COPY ../RealEstateSubscriptionInfo /code

EXPOSE 8085

CMD ["uvicorn","main:app", "--host","0.0.0.0" ,"--port","8085"]
