FROM python:3.9

WORKDIR /code

COPY ../FastApiCore/requirements.txt ./code/requirements.txt

RUN pip install -r ./code/requirements.txt

COPY ../FastApiCore /code

EXPOSE 8082

CMD ["python","main.py"]
