FROM jenkins/jenkins:lts

USER root

# Install required packages
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable" && \
    apt-get update && \
    apt-get install -y docker-ce-cli

# Set up Jenkins plugins
RUN /usr/local/bin/install-plugins.sh \
    kubernetes:1.29.4 \
    docker-workflow:1.26 \
    workflow-aggregator:2.6 \
    git:4.10.0 \
    github:1.33.1

# Set up Jenkins configuration
COPY config/*.groovy /usr/share/jenkins/ref/init.groovy.d/

USER jenkins