FROM python:latest

WORKDIR /code

COPY ../RealEstateCompetitionRate/requirements.txt ./code/requirements.txt

RUN pip install -r ./code/requirements.txt

COPY ../RealEstateCompetitionRate /code

EXPOSE 8086

CMD ["uvicorn","main:app", "--host","0.0.0.0" ,"--port","8086"]
