FROM python:3.9

WORKDIR /code

COPY ../DBClient/requirements.txt ./code/requirements.txt

RUN pip install -r ./code/requirements.txt

COPY ../DBClient /code

EXPOSE 8081

CMD ["uvicorn","main:app", "--host","0.0.0.0" ,"--port","8081"]
