apiVersion: v1
kind: Service
metadata:
  name: fastapi-core
spec:
  selector:
    app: core
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 32223
      targetPort: 8082