apiVersion: v1
kind: Service
metadata:
  name: fastapi-push
spec:
  selector:
    app: push
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8084
      nodePort: 32224
      targetPort: 8084