apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: muyaho/fin-service-fastapi-core