apiVersion: v1
kind: Service
metadata:
  name: realestate-service
spec:
  selector:
    app: realestate
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      nodePort: 32221
      targetPort: 8085