from sqlalchemy import Column, TEXT, INT, BIGINT
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class StockDispositionInfo(Base):
    __tablename__ = "TB_STOCK_DISPOSITION_INFO"
    rcept_no = Column(BIGINT, nullable=False,primary_key=True,unique=True)
    corp_cls = Column(TEXT, nullable=False)
    corp_code = Column(TEXT, nullable=False)
    corp_name = Column(TEXT, nullable=False)
    dppln_stk_ostk = Column(TEXT, nullable=False)
    dppln_stk_estk = Column(TEXT, nullable=False)
    dpstk_prc_ostk = Column(TEXT, nullable=False)
    dpstk_prc_estk = Column(TEXT, nullable=False)
    dppln_prc_ostk = Column(TEXT, nullable=False)
    dppln_prc_estk = Column(TEXT, nullable=False)
    dpprpd_bgd = Column(TEXT, nullable=False)
    dpprpd_edd = Column(TEXT, nullable=False)
    dp_pp = Column(TEXT, nullable=False)
    dp_m_mkt = Column(TEXT, nullable=False)
    dp_m_ovtm = Column(TEXT, nullable=False)
    dp_m_otc = Column(TEXT, nullable=False)
    dp_m_etc = Column(TEXT, nullable=False)
    cs_iv_bk = Column(TEXT, nullable=False)
    aq_wtn_div_ostk = Column(TEXT, nullable=False)
    aq_wtn_div_ostk_rt = Column(TEXT, nullable=False)
    aq_wtn_div_estk = Column(TEXT, nullable=False)
    aq_wtn_div_estk_rt = Column(TEXT, nullable=False)
    eaq_ostk = Column(TEXT, nullable=False)
    eaq_ostk_rt = Column(TEXT, nullable=False)
    eaq_estk = Column(TEXT, nullable=False)
    eaq_estk_rt = Column(TEXT, nullable=False)
    dp_dd = Column(TEXT, nullable=False)
    od_a_at_t = Column(TEXT, nullable=False)
    od_a_at_b = Column(TEXT, nullable=False)
    adt_a_atn = Column(TEXT, nullable=False)
    d1_slodlm_ostk = Column(TEXT, nullable=False)
    d1_slodlm_estk = Column(TEXT, nullable=False)